bridges = []
persistence_dir = '/tmp/tmp.4gjf23IF3m/tryorama/l6han3'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'notes'
keystore_file = '[UNUSED]'
name = 'bob::notes::d2aadb93-29ab-4abf-8e8d-f958f1e13ca0'
public_address = 'HcSCiqoZkSPe8znzzd5nHE46buFYN6ahfmu8IbgBTjmbpo6uxz84Gt3p7K3Ox9r'
test_agent = true

[[dnas]]
file = '/Users/connor/code/holochain/Notes-hApp-Template/dna_src/dist/dna_src.dna.json'
hash = 'QmesLHdkGmihwAD8XNiFNn5PF5d4dBBZkpVMpaAzznFfuB'
id = 'note-test'
uuid = 'd2aadb93-29ab-4abf-8e8d-f958f1e13ca0'

[[instances]]
agent = 'notes'
dna = 'note-test'
id = 'notes'

[instances.storage]
path = '/tmp/tmp.4gjf23IF3m/tryorama/l6han3/notes'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'notes'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
